# Generated by Django 2.2.3 on 2019-08-01 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startUpBanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupbanner',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='startupfield',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startUpBanner.StartUpBanner'),
        ),
    ]
