# Generated by Django 2.2.4 on 2019-08-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=1, max_length=50, verbose_name='last name'),
            preserve_default=False,
        ),
    ]
