# Generated by Django 2.2.3 on 2019-07-31 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='StartUpRegister',
        ),
    ]
