# Generated by Django 2.2.4 on 2019-08-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupregister',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='startupregister',
            name='contact_num',
            field=models.TextField(blank=True, null=True),
        ),
    ]
