# Generated by Django 2.2.3 on 2019-08-02 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20190731_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startupregister',
            old_name='firstname',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='startupregister',
            old_name='lastname',
            new_name='username',
        ),
    ]
