# Generated by Django 2.2.4 on 2019-08-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20190805_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupregister',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='startupregister',
            name='contact_num',
            field=models.TextField(blank=True, null=True),
        ),
    ]
